name: Test Generator
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v7
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup UV
        # v10.2.0
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7
      - name: Sync UV
        run: uv sync
      - name: Run tests with pytest
        run: uv run --frozen pytest
